name: Publish-Crate-Upon-Release
on:
  release:
    types: [published]

jobs:
  publish-automatically:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      -  uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
         with:
           toolchain: stable
           override: true

      - name: publish crates
        run: cargo publish --token ${{ secrets.CARGO_API_TOKEN }}
